// <auto-generated />
using CashRegister.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CashRegister_DAL.Migrations
{
    [DbContext(typeof(CashRegisterContextDB))]
    [Migration("20221011083717_intit")]
    partial class intit
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CashRegister.Models.Einkauf", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Gesamtpreis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Einkauf");
                });

            modelBuilder.Entity("CashRegister.Models.EinkaufsPosition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Anzahl")
                        .HasColumnType("int");

                    b.Property<int>("EinkaufId")
                        .HasColumnType("int");

                    b.Property<int>("ProdukteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EinkaufId");

                    b.HasIndex("ProdukteId");

                    b.ToTable("EinkaufsPosition");
                });

            modelBuilder.Entity("CashRegister.Models.Kategorie", b =>
                {
                    b.Property<int>("KategorieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KategorieId"), 1L, 1);

                    b.Property<string>("KategorieName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MandantId")
                        .HasColumnType("int");

                    b.HasKey("KategorieId");

                    b.HasIndex("MandantId");

                    b.ToTable("Kategorie");

                    b.HasData(
                        new
                        {
                            KategorieId = 1,
                            KategorieName = "Käse",
                            MandantId = 2
                        },
                        new
                        {
                            KategorieId = 2,
                            KategorieName = "Getränk",
                            MandantId = 1
                        });
                });

            modelBuilder.Entity("CashRegister.Models.Mandant", b =>
                {
                    b.Property<int>("MandantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MandantId"), 1L, 1);

                    b.Property<string>("MandantName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MandantId");

                    b.ToTable("Mandant");

                    b.HasData(
                        new
                        {
                            MandantId = 1,
                            MandantName = "Gastro"
                        },
                        new
                        {
                            MandantId = 2,
                            MandantName = "Sennerei"
                        });
                });

            modelBuilder.Entity("CashRegister.Models.Produkt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("KategorieId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Preis")
                        .HasColumnType("float");

                    b.Property<bool>("Preisart")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("KategorieId");

                    b.ToTable("Produkt");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            KategorieId = 1,
                            Name = "Bergkäse",
                            Preis = 20.5,
                            Preisart = true
                        },
                        new
                        {
                            Id = 2,
                            KategorieId = 2,
                            Name = "Kellerbier",
                            Preis = 5.0,
                            Preisart = false
                        });
                });

            modelBuilder.Entity("CashRegister.Models.EinkaufsPosition", b =>
                {
                    b.HasOne("CashRegister.Models.Einkauf", "Einkauf")
                        .WithMany("EinkaufsPosition")
                        .HasForeignKey("EinkaufId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CashRegister.Models.Produkt", "Produkte")
                        .WithMany("EinkaufsPositionen")
                        .HasForeignKey("ProdukteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Einkauf");

                    b.Navigation("Produkte");
                });

            modelBuilder.Entity("CashRegister.Models.Kategorie", b =>
                {
                    b.HasOne("CashRegister.Models.Mandant", "Mandant")
                        .WithMany("Kategorien")
                        .HasForeignKey("MandantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mandant");
                });

            modelBuilder.Entity("CashRegister.Models.Produkt", b =>
                {
                    b.HasOne("CashRegister.Models.Kategorie", "Kategorie")
                        .WithMany("Produkte")
                        .HasForeignKey("KategorieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kategorie");
                });

            modelBuilder.Entity("CashRegister.Models.Einkauf", b =>
                {
                    b.Navigation("EinkaufsPosition");
                });

            modelBuilder.Entity("CashRegister.Models.Kategorie", b =>
                {
                    b.Navigation("Produkte");
                });

            modelBuilder.Entity("CashRegister.Models.Mandant", b =>
                {
                    b.Navigation("Kategorien");
                });

            modelBuilder.Entity("CashRegister.Models.Produkt", b =>
                {
                    b.Navigation("EinkaufsPositionen");
                });
#pragma warning restore 612, 618
        }
    }
}
